modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Creative-Crafter/issues/new/choose"
[[mods]]
modId="creativecrafter"
version="${file.jarVersion}"
displayName="Creative Crafter"
displayURL="https://www.curseforge.com/minecraft/mc-mods/creative-crafter"
logoFile="example.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds a Creative Crafter."

[[dependencies.creativecrafter]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.10.0-beta.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativecrafter]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativecrafter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"